name = "vreya"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN = "vreya-2.myshopify.com"
NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN = "074d0126a43ede70672676e7612ba106"